@host = http://localhost:3001

### POST /api/persons with valid data
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doetest",
  "number": "555-1234"
}

### POST /api/persons with missing name
POST {{host}}/api/persons
Content-Type: application/json

{
  "number": "555-1234"
}

### POST /api/persons with duplicate name
POST {{host}}/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "555-1234"
}
